refresh_rate: 30 seconds

appenders: 
  stdout:
    kind: console
    encoder: 
      kind: pattern
      pattern: "{h({d} [{t}] {f} {m})}{n}"
    filters:
      - kind: threshold
        level: debug

  requests: 
    kind: file
    path: log/dai.log
    encoder:
      pattern: "{h({d} [{t}] {f} {m})}{n}"
    filters:
      - kind: threshold
        level: debug

root:
  level: debug
  appenders:
    - stdout
    - requests

